// react-app/src/components/offline-banner/OfflineBanner.js
import React, { Component } from 'react';
import './OfflineBanner.scss';

/**
 * Banner which warns the user when they are not connected to the internet. The component is only
 * rendered when the user is not online
 */
export default class OfflineBanner extends Component {
  // Hide banner on initial render
  state = {
    isOnline: true
  };

  componentDidMount() {
    // Show banner if browser is offline
    this.setState({
      isOnline: navigator.onLine
    });

    // Update the state when "online"/"offline" events are fired
    window.addEventListener('online', () => this.setState({ isOnline: true }));
    window.addEventListener('offline', () =>
      this.setState({ isOnline: false })
    );
  }

  render() {
    const { isOnline } = this.state;

    // If online: Do not render component
    if (isOnline) {
      return null;
    }

    // If offline: Render banner with warning
    return (
      <div className="offline-banner-outer">
        <div className="offline-banner-inner">
          <p className="offline-banner-content">
            <span role="img" aria-label="Warning">
              ⚠️
            </span>
            &nbsp;
            <span className="offline-banner-title">You are offline.</span>
            &nbsp;
            <span className="offline-banner-msg">
              Please connect to the internet to see the latest information.
            </span>
          </p>
        </div>
      </div>
    );
  }
}

// angular-app/src/app/components/offline-banner/offline-banner.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-offline-banner',
  templateUrl: './offline-banner.component.html',
  styleUrls: ['./offline-banner.component.scss']
})
export class OfflineBannerComponent implements OnInit {
  isOnline: boolean;

  constructor() {}

  ngOnInit() {
    this.isOnline = navigator.onLine;

    // Update `this.isOnline` state when "online"/"offline" events are fired
    window.addEventListener('online', () => {
      this.isOnline = true;
    });
    window.addEventListener('offline', () => {
      this.isOnline = false;
    });
  }
}

<div class="offline-banner-outer" *ngIf="!this.isOnline">
  <div class="offline-banner-inner">
    <p class="offline-banner-content">
      <span role="img" aria-label="Warning">
        ⚠️
      </span>
      &nbsp;
      <span class="offline-banner-title">You are offline.</span>
      &nbsp;
      <span class="offline-banner-msg">
        Please connect to the internet to see the latest information.
      </span>
    </p>
  </div>
</div>
