// react-app/src/components/image/Image.js
import React, {Component} from 'react';
import {MapTo} from '@adobe/cq-react-editable-components';
require('./Image.scss');
/**
 * Default Edit configuration for the Image component that interact with the Core Image component and sub-types
 *
 * @type EditConfig
 */
const ImageEditConfig = {

    emptyLabel: 'Image',

    isEmpty: function(props) {
        return !props || !props.src || props.src.trim().length < 1;
    }
};

/**
 * Image React Component
 * 
 */
export default class Image extends Component {

    get caption() {
        if(this.props.title && this.props.title.length > 0) {
            return <span className="Image-caption">{this.props.title}</span>;
        }
        return null;
    }

    get content() {
        return <img src={this.props.src} alt={this.props.alt}
            title={this.props.displayPopupTitle && this.props.title}/>
    }

    render() {
        return (<div className="Image">
                {this.content}
                {this.caption}
            </div>);
    }
}

MapTo('wknd-events/components/content/image')(Image, ImageEditConfig);

// angular-app/src/app/components/image/image.component.ts
import {Component, Input, OnInit} from '@angular/core';
import {MapTo} from '@adobe/cq-angular-editable-components';

@Component({
  selector: 'app-image',
  templateUrl: './image.component.html',
  styleUrls: ['./image.component.scss']
})
export class ImageComponent implements OnInit {

  @Input() src: string;
  @Input() link: string;
  @Input() alt: string;
  @Input() title: string;
  @Input() displayPopupTitle: string;

  constructor() { }

  get hasImage() {
    return this.src && this.src.trim().length > 0;
  }

  get imageTitle() {
    return this.displayPopupTitle ? this.title : '';
  }

  get imageCaption() {
    return this.title;
  }

  ngOnInit() { }
}

const ImageEditConfig = {
  emptyLabel: 'Image',

  isEmpty: function(componentData) {
    return !componentData || !componentData.src || componentData.src.trim().length < 1;
  }
};

MapTo('wknd-events/components/content/image')(ImageComponent, ImageEditConfig);

<ng-container *ngIf="hasImage">
    <img class="image" [src]="src" [alt]="alt" [title]="imageTitle"/>
    <span class="caption" *ngIf="imageCaption">{{imageCaption}}</span>
  </ng-container>
